//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.default_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean SelectPoint
        {
            get
            {
                return SteamVR_Actions.default_SelectPoint;
            }
        }
        
        public virtual SteamVR_Action_Boolean SegmentMode
        {
            get
            {
                return SteamVR_Actions.default_SegmentMode;
            }
        }
        
        public virtual SteamVR_Action_Boolean ConfirmSegment
        {
            get
            {
                return SteamVR_Actions.default_ConfirmSegment;
            }
        }
        
        public virtual SteamVR_Action_Boolean DeleteLastSegment
        {
            get
            {
                return SteamVR_Actions.default_DeleteLastSegment;
            }
        }
        
        public virtual SteamVR_Action_Boolean PlaceRotButton
        {
            get
            {
                return SteamVR_Actions.default_PlaceRotButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean PlacePressButton
        {
            get
            {
                return SteamVR_Actions.default_PlacePressButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean ConfirmRotation
        {
            get
            {
                return SteamVR_Actions.default_ConfirmRotation;
            }
        }
        
        public virtual SteamVR_Action_Boolean SwitchSymbolMode
        {
            get
            {
                return SteamVR_Actions.default_SwitchSymbolMode;
            }
        }
        
        public virtual SteamVR_Action_Boolean ConfirmSelection
        {
            get
            {
                return SteamVR_Actions.default_ConfirmSelection;
            }
        }
        
        public virtual SteamVR_Action_Boolean DeleteLastSymbol
        {
            get
            {
                return SteamVR_Actions.default_DeleteLastSymbol;
            }
        }
        
        public virtual SteamVR_Action_Boolean ChangeReceiveState
        {
            get
            {
                return SteamVR_Actions.default_ChangeReceiveState;
            }
        }
        
        public virtual SteamVR_Action_Boolean SwitchServerNumber
        {
            get
            {
                return SteamVR_Actions.default_SwitchServerNumber;
            }
        }
        
        public virtual SteamVR_Action_Boolean Manipulate
        {
            get
            {
                return SteamVR_Actions.default_Manipulate;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
